/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Authenticated identity (role derived server-side) */
        get: operations["getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/students": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Students the caller is authorized to see */
        get: operations["getMyStudents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/capabilities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Feature capabilities the backend supports (plan §11) */
        get: operations["getCapabilities"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    [path: `/courses/${string}`]: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Single course the caller is enrolled in / authorized for */
        get: operations["getCourse"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    [path: `/assignments/${string}`]: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Single assignment visible to the caller */
        get: operations["getAssignment"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    [path: `/events/${string}`]: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Calendar event or guidance visit detail (plan item 27) */
        get: operations["getEvent"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    [path: `/forms/${string}/sign`]: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Record a guardian signature (capability-gated - forms) */
        post: operations["signForm"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    [path: `/teacher/classes/${string}/attendance`]: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Period attendance write (capability-gated - teacherAttendanceWrite) */
        post: operations["submitClassAttendance"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    [path: `/teacher/classes/${string}/grading-complete`]: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Clear the pending-grading queue for a section (capability-gated teacherGradingWrite) */
        post: operations["markGradingComplete"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    [path: `/students/${string}/today`]: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Composed Today payload (schedule + derived counts) */
        get: operations["getStudentToday"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    [path: `/students/${string}/courses`]: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getStudentCourses"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    [path: `/students/${string}/assignments`]: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getStudentAssignments"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    [path: `/students/${string}/grades`]: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getStudentGrades"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    [path: `/students/${string}/attendance`]: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getStudentAttendance"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    [path: `/students/${string}/attendance/summary`]: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getStudentAttendanceSummary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    [path: `/courses/${string}/attendance`]: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Period-attendance rows for one course (guardian-of-student scoped) */
        get: operations["getCourseAttendance"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    [path: `/courses/${string}/announcements`]: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Teacher posts for one class (audit P1 — replaces screen-local copy) */
        get: operations["getCourseAnnouncements"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    [path: `/students/${string}/attendance/monthly`]: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getStudentAttendanceMonthly"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    [path: `/students/${string}/absence-reports`]: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getAbsenceReports"];
        put?: never;
        /** Report an absence (only when capabilities.attendanceReporting) */
        post: operations["submitAbsenceReport"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    [path: `/students/${string}/calendar`]: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getStudentCalendar"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    [path: `/students/${string}/guidance`]: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getStudentGuidance"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    [path: `/students/${string}/forms`]: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** District forms awaiting guardian action (capability-gated - forms) */
        get: operations["getStudentForms"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Mailbox for the authenticated viewer (WITSMail semantics) */
        get: operations["getMessages"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    [path: `/messages/threads/${string}/reply`]: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["replyToThread"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    [path: `/messages/threads/${string}/read`]: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["markThreadRead"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/messages/announcements": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Teacher multi-class announcement (fans out one thread per class) */
        post: operations["sendAnnouncement"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/messages/forward": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["forwardMessage"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/staff": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getStaffDirectory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/resources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Student & family resource links */
        get: operations["getResources"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reminders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The caller's personal reminders */
        get: operations["getReminders"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/schedules/bell": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getBellSchedule"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/teacher/today": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getTeacherToday"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/teacher/classes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getTeacherClasses"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    [path: `/teacher/classes/${string}/roster`]: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getTeacherRoster"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness for district IT (plan §280) */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/version": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getVersion"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        User: {
            id: string;
            name: string;
            /** @enum {string} */
            role: "student" | "parent" | "teacher";
            initials: string;
            school: string[];
        };
        Student: {
            id: string;
            name: string;
            initials: string;
            grade: number;
            school: string;
            gpa: number | null;
            attendanceRate: number;
            absences: number;
            tardies: number;
            earlyDismissals: number;
            schoolDays: number;
        };
        Course: {
            id: string;
            name: string;
            teacher: string[];
            /** Format: email */
            teacherEmail: string;
            room: string[];
            period: number;
            meetingTime: string;
            color: string;
            gradePercent: number | null;
            letterGrade: string | null;
            nextDue: string | null;
            description?: string;
            markingPeriods?: components["schemas"]["MarkingPeriod"][];
            gradeCategories?: components["schemas"]["GradeCategory"][];
            announcements?: components["schemas"]["CourseAnnouncement"][];
        };
        GradeCategory: {
            id: string;
            label: string;
            percent: number | null;
        };
        CourseAnnouncement: {
            id: string;
            title: string;
            body: string;
            author: string;
            /** Format: date */
            postedAt: string;
        };
        MarkingPeriod: {
            id: string;
            label: string;
            gradePercent: number | null;
            letterGrade: string | null;
            updated: string;
        };
        Assignment: {
            id: string;
            courseId: string;
            courseName: string;
            title: string;
            description: string;
            /** Format: date */
            dueDate: string | null;
            dueTime: string | null;
            type: string;
            category: string;
            /** @default 100 */
            points: number | null;
            earnedPoints: number | null;
            /** @enum {string} */
            status: "upcoming" | "missing" | "submitted" | "graded" | "no-due-date";
            /** @enum {string} */
            source: "district" | "google-classroom";
            attachments: {
                name: string;
                size: string;
            }[];
            /** Format: date */
            gradedDate: string | null;
        };
        GradeEntry: {
            id: string;
            courseId: string;
            courseName: string;
            assignmentTitle: string;
            earned: number;
            total: number;
            percent: number;
            /** Format: date */
            date: string;
        };
        Reminder: {
            id: string;
            text: string;
        };
        DistrictForm: {
            id: string;
            studentId: string;
            title: string;
            /** @enum {string} */
            type: "permission-slip" | "acknowledgement" | "rsvp" | "conference" | "emergency-contact";
            /** Format: date */
            dueDate: string | null;
            /** @enum {string} */
            status: "awaiting-signature" | "signed";
            /** Format: date-time */
            signedAt: string | null;
            school: string;
            description: string;
        };
        StaffContact: {
            id: string;
            name: string;
            title: string;
        };
        AttendanceRecord: {
            id: string;
            /** Format: date */
            date: string;
            /** @enum {string} */
            status: "present" | "tardy" | "absent" | "early-dismissal";
            note: string | null;
            courseId: string | null;
            arrivalTime: string | null;
            excused: boolean;
            reason: string | null;
            reportedBy: string | null;
            period: number | null;
            departureTime: string | null;
        };
        AttendanceSummary: {
            overall: {
                attendanceRate: number | null;
                absences: number | null;
                tardies: number | null;
                earlyDismissals: number | null;
                schoolDays: number | null;
            };
            byClass: {
                courseId: string;
                absences: number | null;
                tardies: number | null;
                earlyDismissals: number | null;
                attendanceRate: number | null;
            }[];
        };
        MonthlyAttendance: {
            [key: string]: "present" | "tardy" | "absent" | "no-school";
        };
        AbsenceReport: {
            id: string;
            studentId: string;
            /** Format: date */
            date: string;
            /** @enum {string} */
            type: "full-day" | "late-arrival" | "early-dismissal";
            reason: string;
            note: string | null;
            /** Format: date-time */
            submittedAt: string;
            /** @enum {string} */
            status: "submitted" | "acknowledged";
        };
        CalendarEvent: {
            id: string;
            title: string;
            /** Format: date-time */
            start: string;
            /** Format: date-time */
            end: string | null;
            allDay: boolean;
            location: string | null;
            category: string;
            /** @enum {string} */
            source: "course" | "district" | "school" | "club" | "guidance" | "athletics";
            audience: string;
            sourceLabel: string;
            description: string;
            registrationUrl: string | null;
            sourceUrl: string | null;
        };
        GuidanceItem: {
            id: string;
            title: string;
            /** Format: date */
            date: string;
            location: string | null;
            description: string;
            category: string;
            registrationRequired: boolean;
            eligibleGrades: string | null;
            sourceLabel: string;
        };
        Message: {
            id: string;
            sender: string;
            senderId: string | null;
            body: string;
            /** Format: date-time */
            time: string;
            sentByMe: boolean;
            read: boolean;
        };
        MessageThread: {
            id: string;
            participants: string;
            subject: string;
            /** @enum {string} */
            category: "Classes" | "School" | "Clubs";
            unread: boolean;
            preview: string;
            timeLabel: string;
            messages: components["schemas"]["Message"][];
            attachments: {
                name: string;
                size: string;
            }[];
            courseIds: string[];
            authorId: string | null;
            recipientIds: string[];
        };
        ForwardInput: {
            sourceThreadId: string;
            quotedFrom: string;
            quotedDateLabel: string;
            quotedSubject: string;
            quotedBody: string;
            note: string;
            to: ({
                /** @enum {string} */
                kind: "user";
                userId: string;
                label: string;
            } | {
                /** @enum {string} */
                kind: "class";
                courseId: string;
                label: string;
            })[];
        };
        ResourceLink: {
            id: string;
            title: string;
            subtitle: string;
            /** Format: uri */
            url: string;
            icon: string;
        };
        BellPeriod: {
            period: number;
            start: string;
            end: string;
        };
        TodayPayload: {
            meta?: components["schemas"]["PayloadMeta"];
            greetingDateLabel: string;
            dayLabel: string;
            schedule: components["schemas"]["ScheduleBlock"][];
            assignmentsDueCount: number;
            assignmentsDueSoonCount: number;
            eventsTodayCount: number;
            unreadMessagesCount: number;
            announcements: {
                id: string;
                title: string;
                body: string;
            }[];
            recentActivity: {
                id: string;
                title: string;
                subtitle: string;
                timeLabel: string;
            }[];
        };
        PayloadMeta: {
            fetchedAt: string;
            /** @enum {string} */
            source: "demo" | "wits" | "eschooldata" | "guidance" | "finalsite" | "google-classroom";
            stale: boolean;
        };
        ScheduleBlock: {
            courseId: string;
            period: number;
            startTime: string;
            endTime: string;
            /** @enum {string|null} */
            attended: "attended" | "late" | "upcoming" | null;
            arrivalTime: string | null;
        };
        TeacherClass: {
            id: string;
            name: string;
            course?: string;
            period?: number;
            room: string;
            studentCount: number;
            nextMeeting?: string;
            pendingGrading?: number;
            nextAction: string;
        };
        TeacherRosterEntry: {
            id: string;
            name: string;
            gradePercent: number;
            absences: number;
            missingCount: number;
        };
        TeacherScheduleBlock: {
            period: number;
            label: string;
            time: string;
            classId?: string | null;
            /** @enum {string} */
            kind: "class" | "planning" | "duty";
        };
        TeacherActionItem: {
            id: string;
            /** @enum {string} */
            kind: "grading" | "message" | "announcement";
            label: string;
            context: string | null;
            count?: number;
        };
        TeacherTodayPayload: {
            meta?: components["schemas"]["PayloadMeta"];
            teacherName: string;
            dateLabel: string;
            dayLabel: string;
            currentBlock: components["schemas"]["TeacherScheduleBlock"] | unknown;
            nextBlock: components["schemas"]["TeacherScheduleBlock"] | unknown;
            blocks: components["schemas"]["TeacherScheduleBlock"][];
            planningPeriods: components["schemas"]["TeacherScheduleBlock"][];
            totalStudents: number;
            actions: components["schemas"]["TeacherActionItem"][];
            unreadMessages: number;
        };
        Capabilities: {
            messagingReply: boolean;
            messagingCompose: boolean;
            attendanceReporting: boolean;
            teacherAttendanceWrite: boolean;
            teacherGradingWrite: boolean;
            teacherAnnouncements: boolean;
            forms: boolean;
            transportation: boolean;
            lunch: boolean;
            googleClassroomLinks: boolean;
            notificationPush: boolean;
            eventReminders: boolean;
            reportCards: boolean;
        };
    };
    responses: never;
    parameters: {
        /** @description Reuse this key with the same request after an unknown result. The server should store the result for at least 24 hours and reject the same key with a different request body. */
        IdempotencyKey: string;
        CourseId: string;
        StudentId: string;
        ThreadId: string;
        ClassId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current user */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
        };
    };
    getMyStudents: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Linked children (parent) or self (student) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Student"][];
                };
            };
        };
    };
    getCapabilities: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Capability flags */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Capabilities"];
                };
            };
        };
    };
    getCourse: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                courseId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Course */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Course"];
                };
            };
        };
    };
    getAssignment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                assignmentId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Assignment */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Assignment"];
                };
            };
        };
    };
    getEvent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                eventId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Event, or null when no longer available */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CalendarEvent"] | unknown;
                };
            };
        };
    };
    signForm: {
        parameters: {
            query?: never;
            header: {
                /** @description Reuse this key with the same request after an unknown result. The server should store the result for at least 24 hours and reject the same key with a different request body. */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                formId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Updated form */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DistrictForm"];
                };
            };
        };
    };
    submitClassAttendance: {
        parameters: {
            query?: never;
            header: {
                /** @description Reuse this key with the same request after an unknown result. The server should store the result for at least 24 hours and reject the same key with a different request body. */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                classId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Accepted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        ok: boolean;
                    };
                };
            };
        };
    };
    markGradingComplete: {
        parameters: {
            query?: never;
            header: {
                /** @description Reuse this key with the same request after an unknown result. The server should store the result for at least 24 hours and reject the same key with a different request body. */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                classId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Updated class */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeacherClass"];
                };
            };
        };
    };
    getStudentToday: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                studentId: components["parameters"]["StudentId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Today payload */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TodayPayload"];
                };
            };
        };
    };
    getStudentCourses: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                studentId: components["parameters"]["StudentId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Enrolled courses */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Course"][];
                };
            };
        };
    };
    getStudentAssignments: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                studentId: components["parameters"]["StudentId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Assignments across all courses */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Assignment"][];
                };
            };
        };
    };
    getStudentGrades: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                studentId: components["parameters"]["StudentId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Recent grade entries */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GradeEntry"][];
                };
            };
        };
    };
    getStudentAttendance: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                studentId: components["parameters"]["StudentId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Attendance records */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AttendanceRecord"][];
                };
            };
        };
    };
    getStudentAttendanceSummary: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                studentId: components["parameters"]["StudentId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Overall + per-class attendance statistics */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AttendanceSummary"];
                };
            };
        };
    };
    getCourseAttendance: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                courseId: components["parameters"]["CourseId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Attendance records for the course */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AttendanceRecord"][];
                };
            };
        };
    };
    getCourseAnnouncements: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                courseId: components["parameters"]["CourseId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Announcements for the course */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CourseAnnouncement"][];
                };
            };
        };
    };
    getStudentAttendanceMonthly: {
        parameters: {
            query: {
                year: number;
                month: number;
                courseId?: string;
            };
            header?: never;
            path: {
                studentId: components["parameters"]["StudentId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Day-of-month status map */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MonthlyAttendance"];
                };
            };
        };
    };
    getAbsenceReports: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                studentId: components["parameters"]["StudentId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Submitted absence reports */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AbsenceReport"][];
                };
            };
        };
    };
    submitAbsenceReport: {
        parameters: {
            query?: never;
            header: {
                /** @description Reuse this key with the same request after an unknown result. The server should store the result for at least 24 hours and reject the same key with a different request body. */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                studentId: components["parameters"]["StudentId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: date */
                    date: string;
                    /** @enum {string} */
                    type: "full-day" | "late-arrival" | "early-dismissal";
                    reason: string;
                    note?: string | null;
                };
            };
        };
        responses: {
            /** @description Created report */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AbsenceReport"];
                };
            };
        };
    };
    getStudentCalendar: {
        parameters: {
            query?: {
                from?: string;
                to?: string;
            };
            header?: never;
            path: {
                studentId: components["parameters"]["StudentId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Calendar events */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CalendarEvent"][];
                };
            };
        };
    };
    getStudentGuidance: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                studentId: components["parameters"]["StudentId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Guidance items */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GuidanceItem"][];
                };
            };
        };
    };
    getStudentForms: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                studentId: components["parameters"]["StudentId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Forms */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DistrictForm"][];
                };
            };
        };
    };
    getMessages: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Threads visible to the viewer */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageThread"][];
                };
            };
        };
    };
    replyToThread: {
        parameters: {
            query?: never;
            header: {
                /** @description Reuse this key with the same request after an unknown result. The server should store the result for at least 24 hours and reject the same key with a different request body. */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                threadId: components["parameters"]["ThreadId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    body: string;
                };
            };
        };
        responses: {
            /** @description Sent */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        ok: boolean;
                    };
                };
            };
        };
    };
    markThreadRead: {
        parameters: {
            query?: never;
            header: {
                /** @description Reuse this key with the same request after an unknown result. The server should store the result for at least 24 hours and reject the same key with a different request body. */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                threadId: components["parameters"]["ThreadId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Marked read */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        ok: boolean;
                    };
                };
            };
        };
    };
    sendAnnouncement: {
        parameters: {
            query?: never;
            header: {
                /** @description Reuse this key with the same request after an unknown result. The server should store the result for at least 24 hours and reject the same key with a different request body. */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    courseIds: string[];
                    subject: string;
                    body: string;
                };
            };
        };
        responses: {
            /** @description Number of threads created */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        created?: number;
                    };
                };
            };
        };
    };
    forwardMessage: {
        parameters: {
            query?: never;
            header: {
                /** @description Reuse this key with the same request after an unknown result. The server should store the result for at least 24 hours and reject the same key with a different request body. */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ForwardInput"];
            };
        };
        responses: {
            /** @description Number of threads created */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        created?: number;
                    };
                };
            };
        };
    };
    getStaffDirectory: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Directory entries for addressing mail */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StaffContact"][];
                };
            };
        };
    };
    getResources: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Resources */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResourceLink"][];
                };
            };
        };
    };
    getReminders: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Reminders */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Reminder"][];
                };
            };
        };
    };
    getBellSchedule: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Bell periods */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BellPeriod"][];
                };
            };
        };
    };
    getTeacherToday: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Composed teacher day */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeacherTodayPayload"];
                };
            };
        };
    };
    getTeacherClasses: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Authorized sections only */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeacherClass"][];
                };
            };
        };
    };
    getTeacherRoster: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                classId: components["parameters"]["ClassId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Roster (teacher must be authorized for this section) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeacherRosterEntry"][];
                };
            };
        };
    };
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Healthy */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getVersion: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Build metadata */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        version?: string;
                        commit?: string;
                    };
                };
            };
        };
    };
}
